# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Clone Keystore Module
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git clone "https://${GITHUB_TOKEN}@github.com/iamr0s/InstallerBuildData.git" ./buildData

      - name: Previous Build
        run: |
          chmod +x ./gradlew

      - name: Build Debug Apk(s)
        run: |
          ./gradlew assembleDebug --stacktrace

      - name: Build Release Apk(s)
        run: |
          ./gradlew assembleRelease --stacktrace

      - name: Get Build Info
        id: get_build_info
        run: |
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=versionCode::$(grep "versionCode" buildData/version.properties|cut -d'=' -f2)"
          echo "::set-output name=versionName::$(grep "versionName" buildData/version.properties|cut -d'=' -f2)"

      - name: Create A New Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: ${{ steps.get_build_info.outputs.versionName }}
          release_name: ${{ steps.get_build_info.outputs.versionName }}-${{ steps.get_build_info.outputs.sha }}
          body: |
            ${{ steps.get_build_info.outputs.versionName }}-${{ steps.get_build_info.outputs.sha }}
          draft: false
          prerelease: true

      - name: Upload Debug To Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/zip

      - name: Upload Release To Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/zip